const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const elements = {};
function element() { return {textContent: '', innerHTML: '', style: {}, children: [], appendChild(child) { this.children.push(child); }}; }
const document = {getElementById(id) { return elements[id] ??= element(); }, createElement: element, createTextNode(text) { return {textContent:text}; }};
const context = vm.createContext({document});
vm.runInContext(fs.readFileSync('static/quiz.js', 'utf8'), context);
vm.runInContext(`
  const check = (value, expected) => { if (value !== expected) throw new Error(value + ' !== ' + expected); };
  check(currentQuestion, 0);
  goPrevious(); check(currentQuestion, 0);
  saveAnswer(0); goNext(); saveAnswer(1); goPrevious(); check(userAnswers[0], 0);
  saveAnswer(2); check(userAnswers[0], 2);
  goLast(); check(currentQuestion, questions.length - 1);
  goNext(); check(currentQuestion, questions.length - 1);
  goFirst(); check(currentQuestion, 0); check(userAnswers[1], 1);
  userAnswers.fill(undefined); check(calculateScore(), 0);
  check(buildCorrection().split('Your answer: Not answered').length - 1, questions.length);
  for (let i = 0; i < questions.length; i++) userAnswers[i] = questions[i].answer;
  check(calculateScore(), questions.length); check(calculatePercentage(calculateScore()), 100);
  for (let i = 0; i < questions.length; i++) userAnswers[i] = (questions[i].answer + 1) % questions[i].choices.length;
  check(calculateScore(), 0);
  for (let i = 0; i < 5; i++) userAnswers[i] = questions[i].answer;
  check(calculateScore(), 5); check(calculatePercentage(5), 50);
  check(getPerformanceMessage(0), 'Needs improvement'); check(getPerformanceMessage(49), 'Needs improvement');
  check(getPerformanceMessage(50), 'Pass'); check(getPerformanceMessage(59), 'Pass');
  check(getPerformanceMessage(60), 'Good'); check(getPerformanceMessage(79), 'Good');
  check(getPerformanceMessage(80), 'Excellent'); check(getPerformanceMessage(100), 'Excellent');
  check(buildCorrection().split('Explanation:').length - 1, questions.length);
  const count = questions.length; questions.push(questions[0]); check(calculatePercentage(1), 9); questions.pop();
  submitQuiz();
`, context);
assert.equal(elements.quizPanel.style.display, 'none');
assert.equal(elements.resultsPanel.style.display, 'block');
assert.equal(elements.scoreText.textContent, 'Score: 5 / 10');
assert.equal(elements.percentageText.textContent, 'Percentage: 50%');
assert.equal(elements.performanceText.textContent, 'Pass');
assert.match(elements.correction.textContent, /Question 10:/);
console.log('PASS: navigation, saved/changed answers, bounds, zero/full/mixed scores, rounding, every performance boundary, correction, results wiring.');
